// client/src/components/NavBar.vue
<template>
  <div class="nav-holder">
    <div class="nav-holder">
      <div><img src="../assets/folder-icon.png" class="folder-icon" /></div>
      <div>FILE MANAGER</div>
    </div>
    <div>{{ currDate }}</div>
  </div>
</template>

<script>
import Moment from "moment";
const formatDate = "D/M/YYYY hh:mm:ss A";

export default {
  name: "NavBar",
  data() {
    return {
      currDate: Moment().format(formatDate),
    };
  },
  mounted() {
    setInterval(() => {
      this.currDate = Moment().format(formatDate);
    }, 1000);
  },
};
</script>

<style scoped>
div {
  font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
}
.nav-holder {
  display: flex;
  justify-content: space-between;
}
.nav-holder div {
  margin: 0.3em;
}
.folder-icon {
  width: 1em;
  height: 1em;
}
</style>

// client/src/components/NavBar/NavBar.jsx
import styled from 'styled-components';

import folderIcon from '../../assets/folderIcon.jpg'

const NavHolder = styled.div`
    display: flex;
    justify-content: space-between;
`;

const TimeDiv = styled.div`
    margin-right: 1em;
`;

const IconDiv = styled.img`
    margin-left: 1em;
    width: 1.3em;
    height: 1.3em;
`;

const timeFormat = 'DD/MM/YYYY hh:mm:ss A';

function NavBar({ time }) {

    return (
        <NavHolder>
            <IconDiv src={folderIcon} />
            <div>
                File Manager
            </div>
            <TimeDiv>
                {time.format(timeFormat)}
            </TimeDiv>
        </NavHolder>
    );
}

export default NavBar;
